mysql:
  image: mysql:5.6.34
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=symfony
dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
app:
  build: .
  ports:
    - '80:80'
  volumes_from:
    - appdata
  links:
    - "mysql"
appdata:
  image: tianon/true
  volumes:
    - ".:/var/www/html"